# Generated by Django 3.1.1 on 2020-11-03 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view_balances', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
